WEAPON.NAME = "AK-47"
WEAPON.INFORMATION = "Ey Thats P Good"
WEAPON.MODEL = "models/weapons/w_ak74.mdl"
WEAPON.SKIN = 0
WEAPON.SWEP = "cw_poseidon_ak47"
 
WEAPON.SELL = 0
WEAPON.BUY = 0
 
WEAPON.WEIGHT = 5
 
CRAFTINGMOD.WEAPONS:Register(WEAPON)