local WEAPON = {}

WEAPON.NAME = "G36C"
WEAPON.INFORMATION = "A shooty gun"
WEAPON.MODEL = "models/weapons/b_g36.mdl"
WEAPON.SKIN = 0
WEAPON.SWEP = "fas2_g36c"

WEAPON.SELL = 500
WEAPON.BUY = 1000

WEAPON.WEIGHT = 5

CRAFTINGMOD.WEAPONS:Register(WEAPON)