local WEAPON = {}

WEAPON.NAME = "M1911"
WEAPON.INFORMATION = "No one uses these"
WEAPON.MODEL = "models/weapons/b_1911.mdl"
WEAPON.SKIN = 0
WEAPON.SWEP = "fas2_m1911"

WEAPON.SELL = 500
WEAPON.BUY = 1000

WEAPON.WEIGHT = 5

CRAFTINGMOD.WEAPONS:Register(WEAPON)