local WEAPON = {}

WEAPON.NAME = "M24"
WEAPON.INFORMATION = "A sniper"
WEAPON.MODEL = "models/weapons/b_m24.mdl"
WEAPON.SKIN = 0
WEAPON.SWEP = "fas2_m24"

WEAPON.SELL = 500
WEAPON.BUY = 1000

WEAPON.WEIGHT = 5

CRAFTINGMOD.WEAPONS:Register(WEAPON)