WEAPON.NAME = "M249"
WEAPON.INFORMATION = "Ey Thats P Good"
WEAPON.MODEL = "models/weapons/w_m249.mdl"
WEAPON.SKIN = 0
WEAPON.SWEP = "cw_poseidon_m249"
 
WEAPON.SELL = 0
WEAPON.BUY = 0
 
WEAPON.WEIGHT = 5
 
CRAFTINGMOD.WEAPONS:Register(WEAPON)