local WEAPON = {}

WEAPON.NAME = "M3 S90"
WEAPON.INFORMATION = "A cool shotgun"
WEAPON.MODEL = "models/weapons/b_m3s90.mdl"
WEAPON.SKIN = 0
WEAPON.SWEP = "fas2_m3s90"

WEAPON.SELL = 500
WEAPON.BUY = 1000

WEAPON.WEIGHT = 5

CRAFTINGMOD.WEAPONS:Register(WEAPON)