WEAPON.NAME = "M40-A1"
WEAPON.INFORMATION = "Ey Thats P Good"
WEAPON.MODEL = "models/weapons/w_m40.mdl"
WEAPON.SKIN = 0
WEAPON.SWEP = "cw_poseidon_m40a1"
 
WEAPON.SELL = 0
WEAPON.BUY = 0
 
WEAPON.WEIGHT = 5
 
CRAFTINGMOD.WEAPONS:Register(WEAPON)