local WEAPON = {}

WEAPON.NAME = "M4A1"
WEAPON.INFORMATION = "Pew pew"
WEAPON.MODEL = "models/weapons/b_m4.mdl"
WEAPON.SKIN = 0
WEAPON.SWEP = "fas2_m4a1"

WEAPON.SELL = 500
WEAPON.BUY = 1000

WEAPON.WEIGHT = 5

CRAFTINGMOD.WEAPONS:Register(WEAPON)