local WEAPON = {}

WEAPON.NAME = "M82"
WEAPON.INFORMATION = "A sniper"
WEAPON.MODEL = "models/weapons/b_m82.mdl"
WEAPON.SKIN = 0
WEAPON.SWEP = "fas2_m82"

WEAPON.SELL = 500
WEAPON.BUY = 1000

WEAPON.WEIGHT = 5

CRAFTINGMOD.WEAPONS:Register(WEAPON)