local WEAPON = {}

WEAPON.NAME = "MP5A5"
WEAPON.INFORMATION = "A shooty gun"
WEAPON.MODEL = "models/weapons/b_mp5.mdl"
WEAPON.SKIN = 0
WEAPON.SWEP = "fas2_mp5a5"

WEAPON.SELL = 500
WEAPON.BUY = 1000

WEAPON.WEIGHT = 5

CRAFTINGMOD.WEAPONS:Register(WEAPON)