WEAPON.NAME = "MP5K"
WEAPON.INFORMATION = "Ey Thats P Good"
WEAPON.MODEL = "models/weapons/w_mp5k.mdl"
WEAPON.SKIN = 0
WEAPON.SWEP = "cw_poseidon_mp5k"
 
WEAPON.SELL = 0
WEAPON.BUY = 0
 
WEAPON.WEIGHT = 5
 
CRAFTINGMOD.WEAPONS:Register(WEAPON)