local WEAPON = {}

WEAPON.NAME = "Remington 870"
WEAPON.INFORMATION = "Pump it up."
WEAPON.MODEL = "models/weapons/b_870.mdl"
WEAPON.SKIN = 0
WEAPON.SWEP = "fas2_rem870"

WEAPON.SELL = 500
WEAPON.BUY = 1000

WEAPON.WEIGHT = 5

CRAFTINGMOD.WEAPONS:Register(WEAPON)