WEAPON.NAME = "UMP45"
WEAPON.INFORMATION = "Ey Thats P Good"
WEAPON.MODEL = "models/weapons/w_ump45.mdl"
WEAPON.SKIN = 0
WEAPON.SWEP = "cw_poseidon_ump45"
 
WEAPON.SELL = 0
WEAPON.BUY = 0
 
WEAPON.WEIGHT = 5
 
CRAFTINGMOD.WEAPONS:Register(WEAPON)