
local WORKBENCH = {}

WORKBENCH.NAME = "Ammobench"
WORKBENCH.INFORMATION = "A ammo crafting station"
WORKBENCH.MODEL = "models/Items/ammocrate_ar2.mdl"
WORKBENCH.SKIN = 0

WORKBENCH.ENTITY = "craftingmod_workbench" -- DONT CHANGE THIS!

WORKBENCH.SELL = 100
WORKBENCH.BUY = 2000

WORKBENCH.WEIGHT = 5

CRAFTINGMOD.WORKBENCHES:Register(WORKBENCH)
CRAFTINGMOD.ITEMS:Register(WORKBENCH)