local WORKBENCH = {}

WORKBENCH.NAME = "Weaponsmith"
WORKBENCH.INFORMATION = "A carpentry station"
WORKBENCH.MODEL = "models/props_c17/TrapPropeller_Engine.mdl"
WORKBENCH.SKIN = 0

WORKBENCH.ENTITY = "craftingmod_workbench"

WORKBENCH.SELL = 800
WORKBENCH.BUY = 1000

WORKBENCH.WEIGHT = 20

CRAFTINGMOD.WORKBENCHES:Register(WORKBENCH)
CRAFTINGMOD.ITEMS:Register(WORKBENCH)
